import type { Metadata } from "next";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import GoogleWrapper from "@/components/google-wrapper";
import { ActivityTracker } from "@/components/activity-tracker";
import { GlobalBrand } from "@/components/global-brand";
import { ToastProvider } from "@/components/toast-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
      suppressHydrationWarning
    >
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="min-h-full flex flex-col font-inter bg-background text-text-main" suppressHydrationWarning>
        <GoogleWrapper>
          <GlobalBrand />
          {children}
          <ActivityTracker />
          <ToastProvider />
        </GoogleWrapper>
      </body>
    </html>
  );
}
