

import React, { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { CheckCircle, BookOpen, GraduationCap, FileText, Camera, ChevronRight, ChevronLeft, Plus, X, Upload, Eye, AlertCircle, User, ShieldCheck, MapPin, Hash, ClipboardCheck, LogOut } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { useAuthStore } from '@/stores/auth-store'
import { getApiMessage, notifyError, notifySuccess, notifyWarning } from '@/lib/toast'
import Tesseract from 'tesseract.js'

// Available subjects
const SUBJECTS = [
  'Mathematics', 'Physics', 'Chemistry', 'Biology',
  'Computer Science', 'General Science', 'English', 'Urdu', 'Islamiat', 'Pak Studies',
  'Mathematics (FSc)', 'Physics (FSc)', 'Chemistry (FSc)', 'Biology (FSc)',
  'Computer Science (ICS)', 'Statistics (ICS)', 'Economics (FA/ICS)', 
  'Accounting (ICom)', 'Business Math (ICom)', 'Principles of Commerce (ICom)',
  'Education (FA)', 'Sociology (FA)',
  'English (Compulsory)', 'Urdu (Compulsory)', 'Islamic Studies (Compulsory)', 'Pakistan Studies (Compulsory)'
]

// Degree categories
const SCHOOL_DEGREES = [
  'Matriculation (Science)',
  'Matriculation (Arts)',
  'O Levels',
  'A Levels',
  'FSc Pre-Medical',
  'FSc Pre-Engineering',
  'ICS (Computer Science)',
  'ICS (Statistics)',
  'ICS (Physics)',
  'ICom (Commerce)',
  'FA (Arts)',
  'FA (Humanities)',
  'FA (General Science)',
  'DAE Civil',
  'DAE Electrical',
  'DAE Mechanical',
  'DAE Electronics',
  'DAE Computer Information Technology',
  'DAE Chemical',
  'DAE Auto and Diesel',
]

const UNIVERSITY_DEGREES = [
  'ADP Computer Science',
  'ADP Commerce',
  'ADP Arts',
  'ADP Science',
  'ADP Education',
  'BA',
  'BSc',
  'BCom',
  'BBA',
  'BS Accounting and Finance',
  'BS Agriculture',
  'BS Applied Psychology',
  'BS Artificial Intelligence',
  'BS Aviation Management',
  'BS Biochemistry',
  'BS Bioinformatics',
  'BS Biotechnology',
  'BS Botany',
  'BS Business Analytics',

'BS Business Administration',
  'BS Chemistry',
  'BS Civil Engineering',
  'BS Commerce',
  'BS Computer Engineering',
  'BS Computer Science',
  'BS Cyber Security',
  'BS Data Science',
  'BS Economics',
  'BS Education',
  'BS Electrical Engineering',
  'BS Electronics',
  'BS English',
  'BS Environmental Sciences',
  'BS Finance',
  'BS Food Science and Technology',
  'BS Information Technology',
  'BS International Relations',
  'BS Islamic Studies',
  'BS Law',
  'BS Mathematics',
  'BS Mechanical Engineering',
  'BS Media and Communication Studies',
  'BS Microbiology',
  'BS Physics',
  'BS Political Science',
  'BS Psychology',
  'BS Public Administration',
  'BS Software Engineering',
  'BS Sociology',
  'BS Statistics',
  'BS Urdu',
  'BS Zoology',
  'BEd',
  'BEd Hons',
  'LLB',
  'MBBS',
  'BDS',
  'DPT',
  'Pharm D',
  'DVM',
  'BArch',
  'BE Civil Engineering',
  'BE Electrical Engineering',
  'BE Mechanical Engineering',
  'BE Software Engineering',
  'BE Computer Systems Engineering',
  'MSc Mathematics',
  'MSc Physics',
  'MSc Chemistry',
  'MSc Biology',
  'MSc Botany',
  'MSc Zoology',
  'MSc Computer Science',
  'MSc Statistics',
  'MA English',
  'MA Urdu',
  'MA Education',
  'MA Islamic Studies',
  'MA Economics',
  'MA Political Science',
  'MA International Relations',
  'MA Psychology',
  'MA Sociology',
  'MCom',